/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;

/**
 *
 * @author CsaládiAlexandra(SZF
 */
public class KonfigGUI extends javax.swing.JFrame {

    //private static JRadioButton[] rdbNyelvek;
    //private static int nyelvRdbDb
    /**
     * Creates new form KonfigGUI
     */
    public KonfigGUI() {
        initComponents();
        //rdbNyelvek = new JRadioButton[pnlNyelv.getComponentCount()];
        //nyelvRdbDb = rdbNyelv.length;
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        cmbSzak = new javax.swing.JComboBox<>();
        chbHirlevel = new javax.swing.JCheckBox();
        pnlNyelv = new javax.swing.JPanel();
        rgbNyelvJava = new javax.swing.JRadioButton();
        rgbNyelvC = new javax.swing.JRadioButton();
        rgbNyelvPhp = new javax.swing.JRadioButton();
        btnReset = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnBetolt = new javax.swing.JMenuItem();
        mnMentes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnKilepes = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beállítások");
        setType(java.awt.Window.Type.UTILITY);

        cmbSzak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Szak kiválasztása---", "Grafikus", "Szoftver fejlesztő", "Szakács", "Rendszer üzemeltető" }));

        chbHirlevel.setText("hírlevél");

        pnlNyelv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Nyelv"));

        buttonGroup1.add(rgbNyelvJava);
        rgbNyelvJava.setText("Java");

        buttonGroup1.add(rgbNyelvC);
        rgbNyelvC.setText("C#");

        buttonGroup1.add(rgbNyelvPhp);
        rgbNyelvPhp.setText("PHP");

        javax.swing.GroupLayout pnlNyelvLayout = new javax.swing.GroupLayout(pnlNyelv);
        pnlNyelv.setLayout(pnlNyelvLayout);
        pnlNyelvLayout.setHorizontalGroup(
            pnlNyelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNyelvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNyelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rgbNyelvJava)
                    .addComponent(rgbNyelvC)
                    .addComponent(rgbNyelvPhp))
                .addContainerGap())
        );
        pnlNyelvLayout.setVerticalGroup(
            pnlNyelvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNyelvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rgbNyelvJava)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgbNyelvC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rgbNyelvPhp)
                .addContainerGap())
        );

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jMenu4.setText("Konfig");

        mnBetolt.setText("Betöltés");
        mnBetolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBetoltActionPerformed(evt);
            }
        });
        jMenu4.add(mnBetolt);

        mnMentes.setText("Mentés");
        mnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMentesActionPerformed(evt);
            }
        });
        jMenu4.add(mnMentes);
        jMenu4.add(jSeparator1);

        mnKilepes.setText("Kilépés");
        jMenu4.add(mnKilepes);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNyelv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbHirlevel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbSzak, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbSzak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlNyelv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbHirlevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        vezerlokAlaphelyzetbe();
    }//GEN-LAST:event_btnResetActionPerformed

    private void mnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMentesActionPerformed
        //kiírandó tartalom
        String ki = chbHirlevel.isSelected() + "";

        //fájl helyének kiválasztása
        JFileChooser fch = new JFileChooser();
        int v = fch.showSaveDialog(rootPane);
        if (v == JFileChooser.APPROVE_OPTION) {
            File f = fch.getSelectedFile();
            String fn = f.getAbsolutePath(); //"hirleveletKer";
            //fájl kiírása szöveges állományba
            try {
                //fch.showSaveDialog(rootPane);    
                Files.write(Paths.get(fn), ki.getBytes());
            } catch (IOException ex) {
                Logger.getLogger(KonfigGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            //fájl kiírása bináris állományba
            FileOutputStream fajlKi;
            //ObjectOutputStream objKi = new ObjectOutputStream(fn);

            try {
                fajlKi = new FileOutputStream(f);
                ObjectOutputStream objKi = new ObjectOutputStream(fajlKi);
//                fajlKi.write(ki.getBytes());
//                fajlKi.close();
                objKi.writeObject(chbHirlevel);
                objKi.writeObject(cmbSzak);
                objKi.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(KonfigGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(KonfigGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_mnMentesActionPerformed

    private void mnBetoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBetoltActionPerformed
        //fájl helyének kiválasztása
        JFileChooser fch = new JFileChooser();
        int v = fch.showOpenDialog(rootPane);
        if (v == JFileChooser.APPROVE_OPTION) {
            File f = fch.getSelectedFile();
            String fn = f.getAbsolutePath(); //"hirleveletKer";
             //fájl beolvasása bináris állományból
            FileInputStream fajlBe;
            try {
                fajlBe = new FileInputStream(f);
                ObjectInputStream objBe = new ObjectInputStream(fajlBe);
                //Object o = objBe.readObject();
                JCheckBox chb = (JCheckBox) objBe.readObject();
                chbHirlevel.setSelected(chb.isSelected());
                JComboBox cmb = (JComboBox) objBe.readObject();
                cmbSzak.setSelectedIndex(cmb.getSelectedIndex());
                objBe.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(KonfigGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(KonfigGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(KonfigGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_mnBetoltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfigGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfigGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfigGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfigGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfigGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbHirlevel;
    private javax.swing.JComboBox<String> cmbSzak;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnBetolt;
    private javax.swing.JMenuItem mnKilepes;
    private javax.swing.JMenuItem mnMentes;
    private javax.swing.JPanel pnlNyelv;
    private javax.swing.JRadioButton rgbNyelvC;
    private javax.swing.JRadioButton rgbNyelvJava;
    private javax.swing.JRadioButton rgbNyelvPhp;
    // End of variables declaration//GEN-END:variables

    private void vezerlokAlaphelyzetbe() {
        cmbSzak.setSelectedIndex(0);
        chbHirlevel.setSelected(false);
        //teljes buttongroup-ot üríti
        buttonGroup1.clearSelection();
    }
}
